version: "2"
services:
  recommendationservice:
    build: ./
    restart: always
    network_mode: host
    ports:
      - 8081:8081
    expose:
      - 8081

  neo4j:
    image: neo4j:latest
    restart: always
    network_mode: host
    ports:
      - 7474:7474
      - 7687:7687
    expose:
      - 7474
      - 7687